ALTER TABLE `platformGeneralSettings` ADD `loginButtonText` varchar(80);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `heroPrimaryCtaText` varchar(120);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `heroSecondaryCtaText` varchar(120);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineEyebrow` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineStepOneTitle` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineStepOneDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineStepTwoTitle` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineStepTwoDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineStepThreeTitle` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `routineStepThreeDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `benefitOneTitle` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `benefitOneDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `benefitTwoTitle` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `benefitTwoDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `benefitThreeTitle` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `benefitThreeDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `packagesEyebrow` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `packagesTitle` varchar(320);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `packagesDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `packagesLoadingText` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `packagesEmptyText` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `highlightBadgeText` varchar(120);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `includedCoursesLabel` varchar(120);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `planFallbackDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `planAccountNotice` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `finalCtaEyebrow` varchar(160);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `finalCtaTitle` varchar(320);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `finalCtaDescription` text;--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `finalCtaButtonText` varchar(120);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `footerPaymentText` varchar(320);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `heroTextColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `heroMutedTextColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `accentColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `accentTextColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `surfaceColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `cardColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `surfaceAccentColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `borderColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `mutedTextColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `iconBackgroundColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `iconColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `buttonColor` varchar(7);--> statement-breakpoint
ALTER TABLE `platformGeneralSettings` ADD `buttonHoverColor` varchar(7);
