import { useState } from "react";
import { KeyRound, Loader2, ShieldCheck, UserRound, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Input } from "@/components/ui/input";

type AccountUser = { name: string; username: string | null; email: string | null; role: "user" | "admin" };

export function AccountPanel({ user, onClose }: { user: AccountUser; onClose: () => void }) {
  const [profile, setProfile] = useState({ name: user.name, username: user.username ?? "", email: user.email ?? "" });
  const [password, setPassword] = useState({ currentPassword: "", newPassword: "", confirmation: "" });
  const [message, setMessage] = useState<string | null>(null);
  const utils = trpc.useUtils();
  const updateProfile = trpc.auth.updateProfile.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); setMessage("Dados atualizados."); } });
  const changePassword = trpc.auth.changePassword.useMutation({ onSuccess: () => { setPassword({ currentPassword: "", newPassword: "", confirmation: "" }); setMessage("Senha alterada com segurança."); } });
  const pending = updateProfile.isPending || changePassword.isPending;
  const fail = (error: unknown) => setMessage((error as { message?: string })?.message ?? "Não foi possível concluir a atualização.");

  return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#152d38]/55 p-3 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-labelledby="perfil-titulo" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[1.35rem] border border-[#d7cfc1] bg-[#fffdf8] shadow-2xl"><header className="sticky top-0 flex items-start justify-between border-b border-[#e5ddd0] bg-[#fffdf8]/95 p-5 backdrop-blur"><div><p className="eyebrow">CONTA PRIVADA</p><h2 id="perfil-titulo" className="font-display mt-1 text-xl font-bold text-[#173d4a]">Perfil e credencial</h2></div><button onClick={onClose} aria-label="Fechar perfil" className="grid h-9 w-9 place-items-center rounded-xl border border-[#ded6c9]"><X className="h-4 w-4" /></button></header><div className="space-y-6 p-5 sm:p-7">
    <section className="rounded-2xl border border-[#c5dad5] bg-[#f3faf8] p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#0e5a70]"/><p className="text-sm leading-6 text-[#315a5d]">Seus resultados, anotações e histórico ficam associados a esta conta. O perfil administrativo, quando existir, é controlado no servidor.</p></div></section>
    <section><div className="mb-4 flex items-center gap-2"><UserRound className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Dados básicos</h3></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Nome completo<Input value={profile.name} onChange={event => setProfile(value => ({ ...value, name: event.target.value }))} className="mt-1.5 h-11 border-[#cec6b8] bg-white" /></label><label className="text-xs font-bold">Usuário<Input value={profile.username} onChange={event => setProfile(value => ({ ...value, username: event.target.value.toLowerCase() }))} className="mt-1.5 h-11 border-[#cec6b8] bg-white" /></label><label className="text-xs font-bold">E-mail<Input type="email" value={profile.email} onChange={event => setProfile(value => ({ ...value, email: event.target.value }))} className="mt-1.5 h-11 border-[#cec6b8] bg-white" /></label></div><button disabled={pending} onClick={() => updateProfile.mutate(profile, { onError: fail })} className="action-button mt-4 disabled:opacity-60">{updateProfile.isPending && <Loader2 className="h-4 w-4 animate-spin"/>}Salvar dados</button></section>
    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-4 flex items-center gap-2"><KeyRound className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Alterar senha</h3></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Senha atual<Input type="password" autoComplete="current-password" value={password.currentPassword} onChange={event => setPassword(value => ({ ...value, currentPassword: event.target.value }))} className="mt-1.5 h-11 border-[#cec6b8] bg-white" /></label><label className="text-xs font-bold">Nova senha<Input type="password" autoComplete="new-password" value={password.newPassword} onChange={event => setPassword(value => ({ ...value, newPassword: event.target.value }))} className="mt-1.5 h-11 border-[#cec6b8] bg-white" /></label><label className="text-xs font-bold">Confirmar nova senha<Input type="password" autoComplete="new-password" value={password.confirmation} onChange={event => setPassword(value => ({ ...value, confirmation: event.target.value }))} className="mt-1.5 h-11 border-[#cec6b8] bg-white" /></label></div><button disabled={pending} onClick={() => changePassword.mutate(password, { onError: fail })} className="ghost-button mt-4 border-[#97c5bb] text-[#0e5a70] disabled:opacity-60">{changePassword.isPending && <Loader2 className="h-4 w-4 animate-spin"/>}Atualizar senha</button></section>
    {message && <p role="status" className="border border-[#b9d6cb] bg-[#edf8f4] px-3 py-2 text-xs font-semibold text-[#17644e]">{message}</p>}
  </div></section></div>;
}
