import { useMemo, useState } from "react";
import { Check, ClipboardList, CreditCard, Edit3, ImagePlus, Loader2, PackagePlus, ReceiptText, Tag, Trash2, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { resolveCommerceFormError, validatePlanCourseSelection } from "@/lib/planFormValidation";

type PlanForm = { code: string; title: string; description: string; coverImageUrls: string[]; planType: "course_access" | "subscription"; accessDurationDays: number; priceReais: string; isActive: boolean; isHighlighted: boolean; courseIds: string[] };
type CouponForm = { code: string; description: string; discountType: "percentage" | "fixed_amount"; discountValue: string; maxRedemptions: string; startsAt: string; endsAt: string; isActive: boolean };

const initialPlanForm: PlanForm = { code: "", title: "", description: "", coverImageUrls: [], planType: "course_access", accessDurationDays: 365, priceReais: "", isActive: false, isHighlighted: false, courseIds: [] };
const initialCouponForm: CouponForm = { code: "", description: "", discountType: "percentage", discountValue: "", maxRedemptions: "", startsAt: "", endsAt: "", isActive: true };

function formatCurrency(cents: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100); }
function formatDate(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" }) : "—"; }
function toDateInput(value: Date | string | null | undefined) { return value ? new Date(value).toISOString().slice(0, 10) : ""; }
function statusLabel(status: string) { return ({ pending_payment: "Aguardando", paid: "Pago / liberado", cancelled: "Cancelado", expired: "Expirado", refunded: "Estornado" } as Record<string, string>)[status] ?? status; }
function MetricCard({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#d8e6e1] bg-white px-3 py-3"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#5d777d]">{label}</p><p className="mt-1 break-words text-lg font-extrabold text-[#173d4a]">{value}</p></div>; }
function readImageAsBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Não foi possível ler a imagem selecionada."));
    reader.onload = () => typeof reader.result === "string" ? resolve(reader.result.split(",")[1] ?? "") : reject(new Error("Não foi possível ler a imagem selecionada."));
    reader.readAsDataURL(file);
  });
}

export function AdminCommercePanel({ onClose, embedded = false }: { onClose?: () => void; embedded?: boolean }) {
  const utils = trpc.useUtils();
  const courses = trpc.admin.courses.useQuery(undefined, { refetchOnWindowFocus: false });
  const plans = trpc.admin.commerce.plans.useQuery(undefined, { refetchOnWindowFocus: false });
  const coupons = trpc.admin.commerce.coupons.useQuery(undefined, { refetchOnWindowFocus: false });
  const orders = trpc.admin.commerce.orders.useQuery({}, { refetchOnWindowFocus: false });
  const metrics = trpc.admin.commerce.metrics.useQuery(undefined, { refetchOnWindowFocus: false });
  const [planForm, setPlanForm] = useState<PlanForm>(initialPlanForm);
  const [couponForm, setCouponForm] = useState<CouponForm>(initialCouponForm);
  const [editingPlanId, setEditingPlanId] = useState<string | null>(null);
  const [editingCouponId, setEditingCouponId] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const activeCourses = useMemo(() => (courses.data ?? []).filter(course => course.isActive), [courses.data]);
  const refreshCommerce = async () => { await Promise.all([utils.admin.commerce.plans.invalidate(), utils.admin.commerce.coupons.invalidate(), utils.admin.commerce.orders.invalidate(), utils.admin.commerce.metrics.invalidate()]); };
  const fail = (error: unknown) => setNotice(resolveCommerceFormError(error));
  const createPlan = trpc.admin.commerce.createPlan.useMutation({ onSuccess: async () => { await refreshCommerce(); setPlanForm(initialPlanForm); setEditingPlanId(null); setNotice("Plano comercial criado."); }, onError: fail });
  const updatePlan = trpc.admin.commerce.updatePlan.useMutation({ onSuccess: async () => { await refreshCommerce(); setPlanForm(initialPlanForm); setEditingPlanId(null); setNotice("Plano comercial atualizado."); }, onError: fail });
  const createCoupon = trpc.admin.commerce.createCoupon.useMutation({ onSuccess: async () => { await refreshCommerce(); setCouponForm(initialCouponForm); setEditingCouponId(null); setNotice("Cupom criado."); }, onError: fail });
  const updateCoupon = trpc.admin.commerce.updateCoupon.useMutation({ onSuccess: async () => { await refreshCommerce(); setCouponForm(initialCouponForm); setEditingCouponId(null); setNotice("Cupom atualizado."); }, onError: fail });
  const deleteCoupon = trpc.admin.commerce.deleteCoupon.useMutation({ onSuccess: async () => { await refreshCommerce(); setCouponForm(initialCouponForm); setEditingCouponId(null); setNotice("Cupom excluído. Pedidos e transações anteriores foram preservados."); }, onError: fail });
  const approveOrder = trpc.admin.commerce.approveOrder.useMutation({ onSuccess: async () => { await refreshCommerce(); await utils.study.access.invalidate(); setNotice("Pagamento confirmado e matrículas atualizadas."); }, onError: fail });
  const cancelOrder = trpc.admin.commerce.cancelOrder.useMutation({ onSuccess: async () => { await refreshCommerce(); setNotice("Pedido cancelado."); }, onError: fail });
  const uploadPlanImage = trpc.admin.commerce.uploadPlanImage.useMutation({ onSuccess: ({ url }) => { setPlanForm(value => value.coverImageUrls.includes(url) ? value : { ...value, coverImageUrls: [...value.coverImageUrls, url].slice(0, 3) }); setNotice("Imagem de capa adicionada ao plano."); }, onError: fail });
  const pending = createPlan.isPending || updatePlan.isPending || createCoupon.isPending || updateCoupon.isPending || deleteCoupon.isPending || approveOrder.isPending || cancelOrder.isPending || uploadPlanImage.isPending;

  const sendPlan = () => {
    const priceCents = Math.round(Number(planForm.priceReais.replace(",", ".")) * 100);
    if (!Number.isFinite(priceCents) || priceCents < 0) { setNotice("Informe um preço válido em reais."); return; }
    const courseSelectionError = validatePlanCourseSelection(planForm.courseIds);
    if (courseSelectionError) { setNotice(courseSelectionError); return; }
    const input = { code: planForm.code.trim().toUpperCase(), title: planForm.title, description: planForm.description, coverImageUrls: planForm.coverImageUrls, planType: planForm.planType, accessDurationDays: planForm.accessDurationDays, priceCents, isActive: planForm.isActive, isHighlighted: planForm.isHighlighted, courseIds: planForm.courseIds };
    if (editingPlanId) updatePlan.mutate({ id: editingPlanId, data: input }); else createPlan.mutate(input);
  };
  const sendCoupon = () => {
    const discountValue = Math.round(Number(couponForm.discountValue.replace(",", ".")) * (couponForm.discountType === "fixed_amount" ? 100 : 1));
    if (!Number.isFinite(discountValue) || discountValue <= 0) { setNotice("Informe um desconto válido."); return; }
    const input = { code: couponForm.code.trim().toUpperCase(), description: couponForm.description, discountType: couponForm.discountType, discountValue, maxRedemptions: couponForm.maxRedemptions ? Number(couponForm.maxRedemptions) : null, startsAt: couponForm.startsAt ? new Date(`${couponForm.startsAt}T12:00:00`) : null, endsAt: couponForm.endsAt ? new Date(`${couponForm.endsAt}T23:59:59`) : null, isActive: couponForm.isActive };
    if (editingCouponId) updateCoupon.mutate({ id: editingCouponId, data: input }); else createCoupon.mutate(input);
  };
  const editPlan = (plan: NonNullable<typeof plans.data>[number]) => { setEditingPlanId(plan.id); setPlanForm({ code: plan.code, title: plan.title, description: plan.description || "", coverImageUrls: plan.coverImageUrls ?? [], planType: plan.planType, accessDurationDays: plan.accessDurationDays, priceReais: (plan.priceCents / 100).toFixed(2).replace(".", ","), isActive: plan.isActive, isHighlighted: plan.isHighlighted, courseIds: plan.courseIds }); };
  const selectPlanImage = async (file: File | undefined) => {
    if (!file) return;
    if (planForm.coverImageUrls.length >= 3) { setNotice("Cada plano aceita no máximo três imagens de capa."); return; }
    if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setNotice("Selecione uma imagem JPG, PNG ou WEBP."); return; }
    if (file.size > 4 * 1024 * 1024) { setNotice("Envie uma imagem de até 4 MB."); return; }
    try { uploadPlanImage.mutate({ fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp", base64: await readImageAsBase64(file) }); } catch (error) { fail(error); }
  };
  const editCoupon = (coupon: NonNullable<typeof coupons.data>[number]) => { setEditingCouponId(coupon.id); setCouponForm({ code: coupon.code, description: coupon.description || "", discountType: coupon.discountType, discountValue: coupon.discountType === "fixed_amount" ? (coupon.discountValue / 100).toFixed(2).replace(".", ",") : String(coupon.discountValue), maxRedemptions: coupon.maxRedemptions ? String(coupon.maxRedemptions) : "", startsAt: toDateInput(coupon.startsAt), endsAt: toDateInput(coupon.endsAt), isActive: coupon.isActive }); };
  const requestCouponDeletion = (coupon: NonNullable<typeof coupons.data>[number]) => { const confirmation = window.prompt(`Para excluir o cupom ${coupon.code}, digite o código exatamente como exibido.\nPedidos e transações anteriores não serão apagados.`); if (confirmation?.trim().toUpperCase() === coupon.code) deleteCoupon.mutate({ id: coupon.id }); else if (confirmation) setNotice("A confirmação não corresponde ao código do cupom."); };

  return <div className={embedded ? "h-full min-h-0 overflow-y-auto bg-[#fffdf8]" : "fixed inset-0 z-[70] grid place-items-center bg-[#152d38]/60 p-3 backdrop-blur-sm"}><section role={embedded ? undefined : "dialog"} aria-modal={embedded ? undefined : true} aria-labelledby="commerce-admin-title" className={embedded ? "min-h-full w-full bg-[#fffdf8]" : "max-h-[94vh] w-full max-w-7xl overflow-y-auto rounded-[1.4rem] border border-[#c5dad5] bg-[#fffdf8] shadow-2xl"}>
    <header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-[#e6ded1] bg-[#fffdf8]/95 p-5 backdrop-blur sm:p-7"><div><p className="eyebrow">ROOT · OPERAÇÃO COMERCIAL</p><h2 id="commerce-admin-title" className="font-display mt-1 text-xl font-bold text-[#173d4a] sm:text-2xl">Planos, cupons e pedidos</h2><p className="mt-1 text-sm leading-6 text-[#52716f]">Crie ofertas, acompanhe solicitações e libere acessos somente após confirmação de pagamento.</p></div>{!embedded && <button onClick={onClose} aria-label="Fechar gestão comercial" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#d8d0c1] text-[#315a5d]"><X className="h-5 w-5" /></button>}</header>
    <div className="space-y-8 p-5 sm:p-7">{notice && <p role="status" className="rounded-xl border border-[#b9d6cb] bg-[#edf8f4] px-4 py-3 text-sm font-semibold text-[#17644e]">{notice}</p>}
      <section aria-labelledby="commerce-metrics-title" className="rounded-2xl border border-[#c8dcd6] bg-[#f7fbfa] p-5"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><p className="eyebrow">VISÃO COMERCIAL</p><h3 id="commerce-metrics-title" className="font-display mt-1 text-lg font-bold text-[#173d4a]">Indicadores de vendas</h3></div><p className="text-xs text-[#52716f]">Atualização automática após cada operação.</p></div>{metrics.isLoading ? <div className="mt-4 grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-20 animate-pulse rounded-xl bg-[#e8f0ed]" />)}</div> : <div className="mt-4 grid gap-3 sm:grid-cols-3 xl:grid-cols-6"><MetricCard label="Pedidos" value={String(metrics.data?.totalOrders ?? 0)} /><MetricCard label="Pagos" value={String(metrics.data?.paidOrders ?? 0)} /><MetricCard label="Pagamentos" value={String(metrics.data?.approvedPayments ?? 0)} /><MetricCard label="Receita" value={formatCurrency(metrics.data?.revenueCents ?? 0)} /><MetricCard label="Conversão" value={`${metrics.data?.conversionRate ?? 0}%`} /><MetricCard label="Matrículas ativas" value={String(metrics.data?.activeEnrollments ?? 0)} /></div>}</section>
      <div className="grid gap-7 xl:grid-cols-2">
        <section className="rounded-2xl border border-[#c8dcd6] bg-[#f7fbfa] p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><PackagePlus className="h-5 w-5 text-[#0e5a70]" /><h3 className="font-display text-lg font-bold text-[#173d4a]">{editingPlanId ? "Editar plano" : "Novo plano"}</h3></div>{editingPlanId && <button onClick={() => { setEditingPlanId(null); setPlanForm(initialPlanForm); }} className="text-xs font-bold text-[#0e5a70]">Cancelar edição</button>}</div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Nome do plano<input value={planForm.title} onChange={event => setPlanForm(value => ({ ...value, title: event.target.value }))} className="mt-1.5 h-10 w-full rounded-lg border border-[#cbd9d5] bg-white px-3 text-sm" /></label><label className="text-xs font-bold">Código<input value={planForm.code} onChange={event => setPlanForm(value => ({ ...value, code: event.target.value.toUpperCase() }))} placeholder="PF-ANUAL" className="mt-1.5 h-10 w-full rounded-lg border border-[#cbd9d5] bg-white px-3 text-sm font-semibold uppercase" /></label><label className="text-xs font-bold">Preço (R$)<input inputMode="decimal" value={planForm.priceReais} onChange={event => setPlanForm(value => ({ ...value, priceReais: event.target.value }))} placeholder="497,00" className="mt-1.5 h-10 w-full rounded-lg border border-[#cbd9d5] bg-white px-3 text-sm" /></label><label className="text-xs font-bold">Formato<select value={planForm.planType} onChange={event => setPlanForm(value => ({ ...value, planType: event.target.value as PlanForm["planType"] }))} className="mt-1.5 h-10 w-full rounded-lg border border-[#cbd9d5] bg-white px-3 text-sm"><option value="course_access">Curso avulso</option><option value="subscription">Assinatura</option></select></label><label className="text-xs font-bold">Vigência (dias)<input type="number" min="1" max="3650" value={planForm.accessDurationDays} onChange={event => setPlanForm(value => ({ ...value, accessDurationDays: Number(event.target.value) || 1 }))} className="mt-1.5 h-10 w-full rounded-lg border border-[#cbd9d5] bg-white px-3 text-sm" /></label><label className="text-xs font-bold sm:col-span-2">Descrição<textarea value={planForm.description} onChange={event => setPlanForm(value => ({ ...value, description: event.target.value }))} className="mt-1.5 min-h-20 w-full rounded-lg border border-[#cbd9d5] bg-white p-3 text-sm" /></label></div>
          <fieldset className="mt-4"><legend className="text-xs font-bold">Imagens de capa <span className="font-medium text-[#52716f]">({planForm.coverImageUrls.length}/3)</span></legend><p className="mt-1 text-xs leading-5 text-[#52716f]">Estas imagens aparecerão como carrossel na vitrine e no catálogo. JPG, PNG ou WEBP, até 4 MB por imagem.</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{planForm.coverImageUrls.map((url, index) => <div key={url} className="group relative overflow-hidden rounded-xl border border-[#cbd9d5] bg-white"><img src={url} alt={`Prévia da capa ${index + 1}`} className="aspect-[16/10] w-full object-cover" /><button type="button" onClick={() => setPlanForm(value => ({ ...value, coverImageUrls: value.coverImageUrls.filter(imageUrl => imageUrl !== url) }))} aria-label={`Remover imagem ${index + 1}`} className="absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-full bg-[#173d4a]/90 text-white shadow-sm transition hover:bg-[#9d3e2e]"><X className="h-4 w-4" /></button></div>)}{planForm.coverImageUrls.length < 3 && <label className="flex aspect-[16/10] cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-[#86a9a1] bg-white px-3 text-center text-xs font-bold text-[#0e5a70] transition hover:bg-[#edf7f5]"><ImagePlus className="h-5 w-5" /><span>{uploadPlanImage.isPending ? "Enviando..." : "Adicionar imagem"}</span><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={uploadPlanImage.isPending} onChange={event => { void selectPlanImage(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label>}</div></fieldset>
          <fieldset className="mt-4" aria-describedby="plan-courses-help"><div className="flex flex-wrap items-baseline justify-between gap-2"><legend className="text-xs font-bold">Cursos liberados <span className="text-[#9d3e2e]">*</span></legend><span className="text-[11px] font-semibold text-[#52716f]" aria-live="polite">{planForm.courseIds.length} selecionado{planForm.courseIds.length === 1 ? "" : "s"}</span></div><p id="plan-courses-help" className="mt-1 text-xs leading-5 text-[#52716f]">Marque pelo menos um curso para definir qual acesso o comprador receberá.</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{activeCourses.map(course => <label key={course.id} className="flex min-w-0 items-center gap-2 rounded-lg border border-[#dbe7e3] bg-white px-3 py-2 text-xs font-semibold text-[#315a5d]"><input type="checkbox" checked={planForm.courseIds.includes(course.id)} onChange={event => setPlanForm(value => ({ ...value, courseIds: event.currentTarget.checked ? (value.courseIds.includes(course.id) ? value.courseIds : [...value.courseIds, course.id]) : value.courseIds.filter(id => id !== course.id) }))} /><span className="min-w-0 break-words">{course.title}</span></label>)}</div>{!activeCourses.length && <p className="mt-2 text-xs text-[#936422]">Não há cursos ativos para vincular.</p>}</fieldset>
          <div className="mt-4 flex flex-wrap gap-4 text-xs font-bold text-[#315a5d]"><label className="flex items-center gap-2"><input type="checkbox" checked={planForm.isActive} onChange={event => setPlanForm(value => ({ ...value, isActive: event.target.checked }))} />Publicar no catálogo</label><label className="flex items-center gap-2"><input type="checkbox" checked={planForm.isHighlighted} onChange={event => setPlanForm(value => ({ ...value, isHighlighted: event.target.checked }))} />Destacar oferta</label></div><button onClick={sendPlan} disabled={pending} className="action-button mt-5 disabled:opacity-60">{(createPlan.isPending || updatePlan.isPending) && <Loader2 className="h-4 w-4 animate-spin" />}{editingPlanId ? "Salvar plano" : "Criar plano"}</button>
        </section>
        <section className="rounded-2xl border border-[#e4d6ba] bg-[#fffaf0] p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Tag className="h-5 w-5 text-[#936422]" /><h3 className="font-display text-lg font-bold text-[#173d4a]">{editingCouponId ? "Editar cupom" : "Novo cupom"}</h3></div>{editingCouponId && <button onClick={() => { setEditingCouponId(null); setCouponForm(initialCouponForm); }} className="text-xs font-bold text-[#936422]">Cancelar edição</button>}</div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Código<input value={couponForm.code} onChange={event => setCouponForm(value => ({ ...value, code: event.target.value.toUpperCase() }))} placeholder="BEMVINDO" className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm font-semibold uppercase" /></label><label className="text-xs font-bold">Tipo<select value={couponForm.discountType} onChange={event => setCouponForm(value => ({ ...value, discountType: event.target.value as CouponForm["discountType"] }))} className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm"><option value="percentage">Percentual (%)</option><option value="fixed_amount">Valor fixo (R$)</option></select></label><label className="text-xs font-bold">Desconto<input inputMode="decimal" value={couponForm.discountValue} onChange={event => setCouponForm(value => ({ ...value, discountValue: event.target.value }))} placeholder={couponForm.discountType === "percentage" ? "10" : "50,00"} className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm" /></label><label className="text-xs font-bold">Máximo de usos<input type="number" min="1" value={couponForm.maxRedemptions} onChange={event => setCouponForm(value => ({ ...value, maxRedemptions: event.target.value }))} placeholder="Ilimitado" className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm" /></label><label className="text-xs font-bold">Início<input type="date" value={couponForm.startsAt} onChange={event => setCouponForm(value => ({ ...value, startsAt: event.target.value }))} className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm" /></label><label className="text-xs font-bold">Fim<input type="date" value={couponForm.endsAt} onChange={event => setCouponForm(value => ({ ...value, endsAt: event.target.value }))} className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm" /></label><label className="text-xs font-bold sm:col-span-2">Descrição<input value={couponForm.description} onChange={event => setCouponForm(value => ({ ...value, description: event.target.value }))} placeholder="Campanha de lançamento" className="mt-1.5 h-10 w-full rounded-lg border border-[#ddceb0] bg-white px-3 text-sm" /></label></div><label className="mt-4 flex items-center gap-2 text-xs font-bold text-[#315a5d]"><input type="checkbox" checked={couponForm.isActive} onChange={event => setCouponForm(value => ({ ...value, isActive: event.target.checked }))} />Cupom ativo</label><button onClick={sendCoupon} disabled={pending} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#8b5e21] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{(createCoupon.isPending || updateCoupon.isPending) && <Loader2 className="h-4 w-4 animate-spin" />}{editingCouponId ? "Salvar cupom" : "Criar cupom"}</button>
        </section>
      </div>
      <section><div className="mb-4 flex items-center gap-2"><ClipboardList className="h-5 w-5 text-[#0e5a70]" /><h3 className="font-display text-lg font-bold text-[#173d4a]">Planos cadastrados</h3></div>{plans.isLoading ? <p className="text-sm text-[#52716f]">Carregando planos...</p> : !plans.data?.length ? <p className="rounded-xl border border-dashed border-[#cbd9d5] p-4 text-sm text-[#52716f]">Nenhum plano criado.</p> : <div className="grid gap-3 lg:grid-cols-2">{plans.data.map(plan => <article key={plan.id} className="rounded-xl border border-[#d9e4e0] bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold tracking-wider text-[#4b7776]">{plan.code} · {plan.planType === "subscription" ? "ASSINATURA" : "AVULSO"}</p><p className="font-display mt-1 font-bold text-[#173d4a]">{plan.title}</p></div><button onClick={() => editPlan(plan)} aria-label={`Editar plano ${plan.title}`} className="grid h-9 w-9 place-items-center rounded-lg border border-[#b8d3cc] text-[#0e5a70]"><Edit3 className="h-4 w-4" /></button></div><p className="mt-2 text-xs leading-5 text-[#52716f]">{formatCurrency(plan.priceCents)} · {plan.accessDurationDays} dias · {plan.isActive ? "Publicado" : "Rascunho"}</p><p className="mt-2 text-xs font-semibold text-[#315a5d]">Cursos: {plan.courseIds.join(", ")}</p></article>)}</div>}</section>
        <section className="grid gap-7 xl:grid-cols-2"><div><div className="mb-4 flex items-center gap-2"><Tag className="h-5 w-5 text-[#936422]" /><h3 className="font-display text-lg font-bold text-[#173d4a]">Cupons cadastrados</h3></div>{coupons.isLoading ? <p className="text-sm text-[#52716f]">Carregando cupons...</p> : !coupons.data?.length ? <p className="rounded-xl border border-dashed border-[#ddceb0] p-4 text-sm text-[#52716f]">Nenhum cupom criado.</p> : <div className="space-y-2">{coupons.data.map(coupon => <article key={coupon.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#eadfc9] bg-[#fffdfa] p-3"><div className="min-w-0"><p className="font-bold text-[#173d4a]">{coupon.code} <span className="ml-1 text-xs font-medium text-[#7a6650]">{coupon.discountType === "percentage" ? `${coupon.discountValue}%` : formatCurrency(coupon.discountValue)}</span></p><p className="mt-1 text-xs text-[#52716f]">{coupon.isActive ? "Ativo" : "Inativo"} · {coupon.redeemedCount}{coupon.maxRedemptions ? `/${coupon.maxRedemptions}` : ""} uso(s)</p></div><div className="flex shrink-0 gap-2"><button onClick={() => editCoupon(coupon)} aria-label={`Editar cupom ${coupon.code}`} className="grid h-9 w-9 place-items-center rounded-lg border border-[#ddceb0] text-[#936422]"><Edit3 className="h-4 w-4" /></button><button disabled={pending} onClick={() => requestCouponDeletion(coupon)} aria-label={`Excluir cupom ${coupon.code}`} className="grid h-9 w-9 place-items-center rounded-lg border border-[#e4c6bf] text-[#a24932] disabled:opacity-50"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>}</div>
        <div><div className="mb-4 flex items-center gap-2"><ReceiptText className="h-5 w-5 text-[#0e5a70]" /><h3 className="font-display text-lg font-bold text-[#173d4a]">Pedidos recentes</h3></div>{orders.isLoading ? <p className="text-sm text-[#52716f]">Carregando pedidos...</p> : !orders.data?.length ? <p className="rounded-xl border border-dashed border-[#cbd9d5] p-4 text-sm text-[#52716f]">Nenhum pedido registrado.</p> : <div className="space-y-2">{orders.data.map(order => <article key={order.id} className="rounded-xl border border-[#d9e4e0] bg-white p-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="font-bold text-[#173d4a]">{order.item?.titleSnapshot || "Plano"} <span className="text-xs font-medium text-[#52716f]">· {formatCurrency(order.totalCents)}</span></p><p className="mt-1 break-words text-xs text-[#52716f]">{order.buyer?.name || "Conta removida"} · {order.buyer?.email || order.buyer?.username || "sem identificador"}</p><p className="mt-1 text-[10px] text-[#708887]">{order.id} · {formatDate(order.createdAt)}</p></div><span className="w-fit rounded-full bg-[#edf7f5] px-2 py-1 text-[10px] font-bold text-[#17644e]">{statusLabel(order.status)}</span></div>{order.status === "pending_payment" && <div className="mt-3 flex flex-wrap gap-2 border-t border-[#edf1ef] pt-3"><button onClick={() => approveOrder.mutate({ id: order.id })} disabled={pending} className="inline-flex items-center gap-1.5 rounded-lg bg-[#17644e] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{approveOrder.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />}Confirmar pagamento</button><button onClick={() => cancelOrder.mutate({ id: order.id })} disabled={pending} className="rounded-lg border border-[#d8c8c8] px-3 py-2 text-xs font-bold text-[#875555] disabled:opacity-60">Cancelar</button></div>}</article>)}</div>}</div>
      </section>
      <section className="flex gap-3 rounded-2xl border border-[#d4dfdb] bg-[#f7fbfa] p-4"><CreditCard className="mt-0.5 h-5 w-5 shrink-0 text-[#0e5a70]" /><p className="text-xs leading-6 text-[#52716f]">A confirmação manual é uma etapa operacional temporária. Ao conectar um provedor, o webhook validado deverá chamar a mesma regra de aprovação, sem liberar matrícula com base apenas no retorno do navegador.</p></section>
    </div>
  </section></div>;
}
