import { BookOpenCheck, Search, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { KnowledgeBaseManager } from "@/components/KnowledgeBaseManager";
import { existingQuestionEditingSteps, rootAdminAreas } from "@/lib/rootAdminNavigation";

export function AdminLibraryPanel({ onClose }: { onClose: () => void }) {
  const coursesQuery = trpc.admin.courses.useQuery();

  return <div className="fixed inset-0 z-[70] bg-[#152d38]/65 p-3 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-labelledby="biblioteca-titulo" className="mx-auto flex h-[calc(100vh-1.5rem)] w-full max-w-7xl flex-col overflow-hidden rounded-[1.35rem] border border-[#274a54] bg-[#fffdf8] shadow-2xl"><header className="flex items-start justify-between border-b border-[#d8d0c4] bg-[#183542] p-5 text-white"><div><p className="text-[10px] font-bold tracking-[0.2em] text-[#99d8ca]">ROOT / BIBLIOTECA CENTRAL</p><h2 id="biblioteca-titulo" className="font-display mt-1 text-xl font-bold">{rootAdminAreas.library.title}</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-[#d3e6e1]">Esta área é independente da gestão de alunos. Ela abre em <b>Todas as questões</b>: pesquise pelo enunciado, filtre o status e clique em <b>Editar questão</b> no cartão encontrado.</p></div><button onClick={onClose} aria-label="Fechar biblioteca" className="grid h-9 w-9 place-items-center rounded-xl border border-white/25 text-white"><X className="h-4 w-4" /></button></header><div className="min-h-0 flex-1 overflow-y-auto p-5 sm:p-6"><div className="mb-5 grid gap-3 border border-[#c8dcd6] bg-[#edf7f4] p-4 md:grid-cols-3"><div className="flex gap-2"><Search className="mt-0.5 h-4 w-4 shrink-0 text-[#0e5a70]"/><p className="text-xs leading-5 text-[#365e61]"><b>1. Localize.</b><br/>{existingQuestionEditingSteps[0]}</p></div><div className="flex gap-2"><BookOpenCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#0e5a70]"/><p className="text-xs leading-5 text-[#365e61]"><b>2. Edite.</b><br/>{existingQuestionEditingSteps[1]}</p></div><div className="text-xs leading-5 text-[#365e61]"><b>3. Salve o histórico.</b><br/>{existingQuestionEditingSteps[2]}</div></div><KnowledgeBaseManager courses={coursesQuery.data ?? []}/></div></section></div>;
}
