import { Filter, Search, X } from "lucide-react";
import { marketplaceFilterOptions, type CourseMarketplaceFilters } from "@/lib/courseMarketplace";
import type { PublicStorefrontPlan } from "@/lib/publicStorefront";

export function CourseFilterToolbar({ plans, filters, onChange, compact = false }: { plans: PublicStorefrontPlan[]; filters: CourseMarketplaceFilters; onChange: (next: CourseMarketplaceFilters) => void; compact?: boolean }) {
  const options = marketplaceFilterOptions(plans);
  const set = <K extends keyof CourseMarketplaceFilters>(key: K, value: CourseMarketplaceFilters[K]) => onChange({ ...filters, [key]: value });
  const clear = () => onChange({ search: "", state: "", area: "", kind: "all" });
  return <div className={`rounded-2xl border border-[#c8dcd6] bg-[#edf7f5] ${compact ? "p-3" : "p-4"}`}><div className="flex items-center justify-between gap-3"><p className="flex items-center gap-2 text-sm font-bold text-[#173d4a]"><Filter className="h-4 w-4 text-[#0e5a70]" />Filtrar cursos</p><button type="button" onClick={clear} className="inline-flex items-center gap-1 text-xs font-bold text-[#0e5a70] hover:underline"><X className="h-3.5 w-3.5" />Limpar</button></div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[#63807d]" /><input value={filters.search} onChange={event => set("search", event.target.value)} placeholder="Nome do curso ou tema" className="h-10 w-full rounded-xl border border-[#cfc7ba] bg-white pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-[#82cfbf]" /></label><select aria-label="Filtrar por estado" value={filters.state} onChange={event => set("state", event.target.value)} className="h-10 rounded-xl border border-[#cfc7ba] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#82cfbf]"><option value="">Todos os estados</option>{options.states.map(state => <option key={state} value={state}>{state}</option>)}</select><select aria-label="Filtrar por área" value={filters.area} onChange={event => set("area", event.target.value)} className="h-10 rounded-xl border border-[#cfc7ba] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#82cfbf]"><option value="">Todas as áreas</option>{options.areas.map(area => <option key={area} value={area}>{area}</option>)}</select><select aria-label="Filtrar por tipo" value={filters.kind} onChange={event => set("kind", event.target.value as CourseMarketplaceFilters["kind"])} className="h-10 rounded-xl border border-[#cfc7ba] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#82cfbf]"><option value="all">Concursos e Tutoriais</option><option value="concurso">Somente concursos</option><option value="tutorial">Somente Tutoriais</option></select></div></div>;
}
